# Note that this project takes place in R

The Nobel Prize has been among the most prestigious international awards since 1901. Each year, awards are bestowed in chemistry, literature, physics, physiology or medicine, economics, and peace. In addition to the honor, prestige, and substantial prize money, the recipient also gets a gold medal with an image of Alfred Nobel (1833 - 1896), who established the prize.

![](Nobel_Prize.png)

The Nobel Foundation has made a dataset available of all prize winners from the outset of the awards from 1901 to 2023. The dataset used in this project is from the Nobel Prize API and is available in the `nobel.csv` file in the `data` folder.

In this project, you'll get a chance to explore and answer several questions related to this prize-winning data. And we encourage you then to explore further questions that you're interested in!

In [75]:
# Loading in required libraries
library(tidyverse)
library(readr)
library(ggplot2)

In [76]:
#read in the data
nobel = read_csv("data/nobel.csv")
glimpse(nobel)
nobel

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Rows: 1000 Columns: 18
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (14): category, prize, motivation, prize_share, laureate_type, full_nam...
dbl   (2): year, laureate_id
date  (2): birth_date, death_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 1,000
Columns: 18
$ year                 <dbl> 1901, 1901, 1901, 1901, 1901, 1901, 1902, 1902, 1…
$ category             <chr> "Chemistry", "Literature", "Medicine", "Peace", "…
$ prize                <chr> "The Nobel Prize in Chemistry 1901", "The Nobel P…
$ motivation           <chr> "\"in recognition of the extraordinary services h…
$ prize_share          <chr> "1/1", "1/1", "1/1", "1/2", "1/2", "1/1", "1/1", …
$ laureate_id          <dbl> 160, 569, 293, 462, 463, 1, 161, 571, 294, 464, 4…
$ laureate_type        <chr> "Individual", "Individual", "Individual", "Indivi…
$ full_name            <chr> "Jacobus Henricus van 't Hoff", "Sully Prudhomme"…
$ birth_date           <date> 1852-08-30, 1839-03-16, 1854-03-15, 1828-05-08, …
$ birth_city           <chr> "Rotterdam", "Paris", "Hansdorf (Lawice)", "Genev…
$ birth_country        <chr> "Netherlands", "France", "Prussia (Poland)", "Swi…
$ sex                  <chr> "Male", "Male", "Male", "Male", "Male", "Male", "…
$ organization_name    <chr> "Berlin University", NA, "Marburg University", NA…
$ organization_city    <chr> "Berlin", NA, "Marburg", NA, NA, "Munich", "Berli…
$ organization_country <chr> "Germany", NA, "Germany", NA, NA, "Germany", "Ger…
$ death_date           <date> 1911-03-01, 1907-09-07, 1917-03-31, 1910-10-30, …
$ death_city           <chr> "Berlin", "Châtenay", "Marburg", "Heiden", "Paris…
$ death_country        <chr> "Germany", "France", "Germany", "Switzerland", "F…

     year category   prize
1    1901 Chemistry  The Nobel Prize in Chemistry 1901
2    1901 Literature The Nobel Prize in Literature 1901
3    1901 Medicine   The Nobel Prize in Physiology or Medicine 1901
4    1901 Peace      The Nobel Peace Prize 1901
5    1901 Peace      The Nobel Peace Prize 1901
6    1901 Physics    The Nobel Prize in Physics 1901
7    1902 Chemistry  The Nobel Prize in Chemistry 1902
8    1902 Literature The Nobel Prize in Literature 1902
9    1902 Medicine   The Nobel Prize in Physiology or Medicine 1902
10   1902 Peace      The Nobel Peace Prize 1902
11   1902 Peace      The Nobel Peace Prize 1902
12   1902 Physics    The Nobel Prize in Physics 1902
13   1902 Physics    The Nobel Prize in Physics 1902
14   1903 Chemistry  The Nobel Prize in Chemistry 1903
15   1903 Literature The Nobel Prize in Literature 1903
16   1903 Medicine   The Nobel Prize in Physiology or Medicine 1903
17   1903 Peace      The Nobel Peace Prize 1903
18   1903 Physics    The Nobel Prize in Physics 1903
19   1903 Physics    The Nobel Prize in Physics 1903
20   1903 Physics    The Nobel Prize in Physics 1903
21   1904 Chemistry  The Nobel Prize in Chemistry 1904
22   1904 Literature The Nobel Prize in Literature 1904
23   1904 Literature The Nobel Prize in Literature 1904
24   1904 Medicine   The Nobel Prize in Physiology or Medicine 1904
25   1904 Peace      The Nobel Peace Prize 1904
26   1904 Physics    The Nobel Prize in Physics 1904
27   1905 Chemistry  The Nobel Prize in Chemistry 1905
28   1905 Literature The Nobel Prize in Literature 1905
29   1905 Medicine   The Nobel Prize in Physiology or Medicine 1905
30   1905 Peace      The Nobel Peace Prize 1905
⋮    ⋮    ⋮          ⋮
971  2021 Peace      The Nobel Peace Prize 2021
972  2021 Peace      The Nobel Peace Prize 2021
973  2021 Economics  The Sveriges Riksbank Prize in Economic Sciences 2021
974  2021 Economics  The Sveriges Riksbank Prize in Economic Sciences 2021
975  2021 Economics  The Sveriges Riksbank Prize in Economic Sciences 2021
976  2022 Chemistry  The Nobel Prize in Chemistry 2022
977  2022 Medicine   The Nobel Prize in Physiology or Medicine 2022
978  2022 Physics    The Nobel Prize in Physics 2022
979  2022 Physics    The Nobel Prize in Physics 2022
980  2022 Physics    The Nobel Prize in Physics 2022
981  2022 Chemistry  The Nobel Prize in Chemistry 2022
982  2022 Chemistry  The Nobel Prize in Chemistry 2022
983  2022 Literature The Nobel Prize in Literature 2022
984  2022 Peace      The Nobel Peace Prize 2022
985  2022 Peace      The Nobel Peace Prize 2022
986  2022 Peace      The Nobel Peace Prize 2022
987  2022 Economics  The Sveriges Riksbank Prize in Economic Sciences 2022
988  2022 Economics  The Sveriges Riksbank Prize in Economic Sciences 2022
989  2022 Economics  The Sveriges Riksbank Prize in Economic Sciences 2022
990  2023 Medicine   The Nobel Prize in Physiology or Medicine 2023
991  2023 Medicine   The Nobel Prize in Physiology or Medicine 2023
992  2023 Physics    The Nobel Prize in Physics 2023
993  2023 Physics    The Nobel Prize in Physics 2023
994  2023 Physics    The Nobel Prize in Physics 2023
995  2023 Chemistry  The Nobel Prize in Chemistry 2023
996  2023 Chemistry  The Nobel Prize in Chemistry 2023
997  2023 Chemistry  The Nobel Prize in Chemistry 2023
998  2023 Literature The Nobel Prize in Literature 2023
999  2023 Peace      The Nobel Peace Prize 2023
1000 2023 Economics  The Sveriges Riksbank Prize in Economic Sciences 2023
     motivation
1    "in recognition of the extraordinary services he has rendered by the discovery of the laws of chemical dynamics and osmotic pressure in solutions"
2    "in special recognition of his poetic composition, which gives evidence of lofty idealism, artistic perfection and a rare combination of the qualities of both heart and intellect"
3    "for his work on serum therapy, especially its application against diphtheria, by which he has opened a new road in the domain of medical science and thereby placed in the hands of the physician a victorious weapon against illness and deaths"
4    NA
5    NA
6    "in recognition of the extraordinary services he has rendered by the discovery of the remarkable rays subsequently named after him"
7    "in recognition of the extraordinary services he has rendered by his work on sugar and purine syntheses"
8    "the greatest living master of the art of historical writing, with special reference to his monumental work, <I>A history of Rome</I>"
9    "for his work on malaria, by which he has shown how it enters the organism and thereby has laid the foundation for successful research on this disease and methods of combating it"
10   NA
11   NA
12   "in recognition of the extraordinary service they rendered by their researches into the influence of magnetism upon radiation phenomena"
13   "in recognition of the extraordinary service they rendered by their researches into the influence of magnetism upon radiation phenomena"
14   "in recognition of the extraordinary services he has rendered to the advancement of chemistry by his electrolytic theory of dissociation"
15   "as a tribute to his noble, magnificent and versatile poetry, which has always been distinguished by both the freshness of its inspiration and the rare purity of its spirit"
16   "in recognition of his contribution to the treatment of diseases, especially lupus vulgaris, with concentrated light radiation, whereby he has opened a new avenue for medical science"
17   NA
18   "in recognition of the extraordinary services he has rendered by his discovery of spontaneous radioactivity"
19   "in recognition of the extraordinary services they have rendered by their joint researches on the radiation phenomena discovered by Professor Henri Becquerel"
20   "in recognition of the extraordinary services they have rendered by their joint researches on the radiation phenomena discovered by Professor Henri Becquerel"
21   "in recognition of his services in the discovery of the inert gaseous elements in air, and his determination of their place in the periodic system"
22   "in recognition of the fresh originality and true inspiration of his poetic production, which faithfully reflects the natural scenery and native spirit of his people, and, in addition, his significant work as a Proven&ccedil;al philologist"
23   "in recognition of the numerous and brilliant compositions which, in an individual and original manner, have revived the great traditions of the Spanish drama"
24   "in recognition of his work on the physiology of digestion, through which knowledge on vital aspects of the subject has been transformed and enlarged"
25   NA
26   "for his investigations of the densities of the most important gases and for his discovery of argon in connection with these studies"
27   "in recognition of his services in the advancement of organic chemistry and the chemical industry, through his work on organic dyes and hydroaromatic compounds"
28   "because of his outstanding merits as an epic writer"
29   "for his investigations and discoveries in relation to tuberculosis"
30   NA
⋮    ⋮
971  "for their efforts to safeguard freedom of expression which is a precondition for democracy and lasting peace"
972  "for their efforts to safeguard freedom of expression which is a precondition for democracy and lasting peace"
973  "for his empirical contributions to labour economics"
974  "for their methodological contributions to the analysis of causal relationships"
975  "for their methodological contributions to the analysis of causal relationships"
976  "for the development of click chemistry and bioorthogonal chemistry"
977  "for his discoveries concerning the genomes of extinct hominins and human evolution"
978  "for experiments with entangled photons establishing the violation of Bell inequalities and  pioneering quantum information science"
979  "for experiments with entangled photons establishing the violation of Bell inequalities and  pioneering quantum information science"
980  "for experiments with entangled photons establishing the violation of Bell inequalities and  pioneering quantum information science"
981  "for the development of click chemistry and bioorthogonal chemistry"
982  "for the development of click chemistry and bioorthogonal chemistry"
983  "for the courage and clinical acuity with which she uncovers the roots estrangements and  collective restraints of personal memory"
984  "The Peace Prize laureates represent civil society in their home countries. They have for many years promoted the right to criticise power and protect the fundamental rights of citizens. They have made an outstanding effort to document war crimes human right abuses and the abuse of power. Together they demonstrate the significance of civil society for peace and democracy."
985  "The Peace Prize laureates represent civil society in their home countries. They have for many years promoted the right to criticise power and protect the fundamental rights of citizens. They have made an outstanding effort to document war crimes human right abuses and the abuse of power. Together they demonstrate the significance of civil society for peace and democracy."
986  "The Peace Prize laureates represent civil society in their home countries. They have for many years promoted the right to criticise power and protect the fundamental rights of citizens. They have made an outstanding effort to document war crimes human right abuses and the abuse of power. Together they demonstrate the significance of civil society for peace and democracy."
987  "for research on banks and financial crises"
988  "for research on banks and financial crises"
989  "for research on banks and financial crises"
990  "for their discoveries concerning nucleoside base modifications that enabled the development of effective mRNA vaccines against COVID-19"
991  "for their discoveries concerning nucleoside base modifications that enabled the development of effective mRNA vaccines against COVID-19"
992  "for experimental methods that generate attosecond pulses of light for the study of electron dynamics in matter"
993  "for experimental methods that generate attosecond pulses of light for the study of electron dynamics in matter"
994  "for experimental methods that generate attosecond pulses of light for the study of electron dynamics in matter"
995  "for the discovery and synthesis of quantum dots"
996  "for the discovery and synthesis of quantum dots"
997  "for the discovery and synthesis of quantum dots"
998  "for his innovative plays and prose which give voice to the unsayable"
999  "for her fight against the oppression of women in Iran and her fight to promote human rights and freedom for all"
1000 "for having advanced our understanding of women’s labour market outcomes"
     prize_share laureate_id laureate_type
1    1/1         160         Individual
2    1/1         569         Individual
3    1/1         293         Individual
4    1/2         462         Individual
5    1/2         463         Individual
6    1/1           1         Individual
7    1/1         161         Individual
8    1/1         571         Individual
9    1/1         294         Individual
10   1/2         464         Individual
11   1/2         465         Individual
12   1/2           2         Individual
13   1/2           3         Individual
14   1/1         162         Individual
15   1/1         572         Individual
16   1/1         295         Individual
17   1/1         466         Individual
18   1/2           4         Individual
19   1/4           5         Individual
20   1/4           6         Individual
21   1/1         163         Individual
22   1/2         573         Individual
23   1/2         574         Individual
24   1/1         296         Individual
25   1/1         467         Organization
26   1/1           8         Individual
27   1/1         164         Individual
28   1/1         575         Individual
29   1/1         297         Individual
30   1/1         468         Individual
⋮    ⋮           ⋮           ⋮
971  1/2         1005        Individual
972  1/2         1006        Individual
973  1/2         1007        Individual
974  1/4         1008        Individual
975  1/4         1009        Individual
976  1/3          743        Individual
977  1/1         1011        Individual
978  1/3         1012        Individual
979  1/3         1013        Individual
980  1/3         1014        Individual
981  1/3         1015        Individual
982  1/3         1016        Individual
983  1/1         1017        Individual
984  1/3         1018        Individual
985  1/3         1019        Organization
986  1/3         1020        Organization
987  1/3         1021        Individual
988  1/3         1022        Individual
989  1/3         1023        Individual
990  1/2         1024        Individual
991  1/2         1025        Individual
992  1/3         1026        Individual
993  1/3         1027        Individual
994  1/3         1028        Individual
995  1/3         1029        Individual
996  1/3         1030        Individual
997  1/3         1031        Individual
998  1/1         1032        Individual
999  1/1         1033        Individual
1000 1/1         1034        Individual
     full_name
1    Jacobus Henricus van 't Hoff
2    Sully Prudhomme
3    Emil Adolf von Behring
4    Jean Henry Dunant
5    Frédéric Passy
6    Wilhelm Conrad Röntgen
7    Hermann Emil Fischer
8    Christian Matthias Theodor Mommsen
9    Ronald Ross
10   Élie Ducommun
11   Charles Albert Gobat
12   Hendrik Antoon Lorentz
13   Pieter Zeeman
14   Svante August Arrhenius
15   Bjørnstjerne Martinus Bjørnson
16   Niels Ryberg Finsen
17   William Randal Cremer
18   Antoine Henri Becquerel
19   Pierre Curie
20   Marie Curie, née Sklodowska
21   Sir William Ramsay
22   Frédéric Mistral
23   José Echegaray y Eizaguirre
24   Ivan Petrovich Pavlov
25   Institut de droit international (Institute of International Law)
26   Lord Rayleigh (John William Strutt)
27   Johann Friedrich Wilhelm Adolf von Baeyer
28   Henryk Sienkiewicz
29   Robert Koch
30   Baroness Bertha Sophie Felicita von Suttner, née Countess Kinsky von Chinic und Tettau
⋮    ⋮
971  Maria Ressa
972  Dmitry Muratov
973  David Card
974  Joshua Angrist
975  Guido Imbens
976  Barry Sharpless
977  Svante Pääbo
978  Alain Aspect
979  John Clauser
980  Anton Zeilinger
981  Carolyn Bertozzi
982  Morten Meldal
983  Annie Ernaux
984  Ales Bialiatski
985  Memorial
986  Center for Civil Liberties
987  Ben Bernanke
988  Douglas Diamond
989  Philip Dybvig
990  Katalin Karikó
991  Drew Weissman
992  Pierre Agostini
993  Ferenc Krausz
994  Anne L’Huillier
995  Moungi Bawendi
996  Louis Brus
997  Aleksey Yekimov
998  Jon Fosse
999  Narges Mohammadi
1000 Claudia Goldin
     birth_date birth_city
1    1852-08-30 Rotterdam
2    1839-03-16 Paris
3    1854-03-15 Hansdorf (Lawice)
4    1828-05-08 Geneva
5    1822-05-20 Paris
6    1845-03-27 Lennep (Remscheid)
7    1852-10-09 Euskirchen
8    1817-11-30 Garding
9    1857-05-13 Almora
10   1833-02-19 Geneva
11   1843-05-21 Tramelan
12   1853-07-18 Arnhem
13   1865-05-25 Zonnemaire
14   1859-02-19 Vik
15   1832-12-08 Kvikne
16   1860-12-15 Thorshavn
17   1828-03-18 Fareham
18   1852-12-15 Paris
19   1859-05-15 Paris
20   1867-11-07 Warsaw
21   1852-10-02 Glasgow
22   1830-09-08 Maillane
23   1832-04-19 Madrid
24   1849-09-14 Ryazan
25   <NA>       NA
26   1842-11-12 Langford Grove, Maldon, Essex
27   1835-10-31 Berlin
28   1846-05-05 Wola Okrzejska
29   1843-12-11 Clausthal (Clausthal-Zellerfeld)
30   1843-06-09 Prague
⋮    ⋮          ⋮
971  1963-10-02 Manila
972  <NA>       Kubyshev (now Samara)
973  <NA>       Guelph
974  1960-09-18 Columbus, OH
975  1963-09-03 Geldrop
976  1941-04-28 Philadelphia, PA
977  1955-04-20 Stockholm
978  1947-06-15 Agen
979  1942-12-01 Pasadena, CA
980  1945-05-20 Ried im Innkreis
981  1966-10-10 Boston, MA
982  <NA>       Copenhagen
983  1940-09-01 Lillebonne
984  1962-09-25 Vyartsilya Karelia
985  <NA>       NA
986  <NA>       NA
987  1953-12-13 Augusta, GA
988  1953-10-25 Chicago, IL
989  1955-05-22 Gainesville, FL
990  1955-01-17 Szolnok
991  1959-09-07 Lexington, MA
992  1941-07-23 Tunis
993  1962-05-17 Mór
994  1958-08-16 Paris
995  <NA>       Paris
996  <NA>       Cleveland, OH
997  <NA>       NA
998  1959-09-29 Haugesund
999  1972-04-21 Zanjan
1000 <NA>       New York, NY
     birth_country                                sex
1    Netherlands                                  Male
2    France                                       Male
3    Prussia (Poland)                             Male
4    Switzerland                                  Male
5    France                                       Male
6    Prussia (Germany)                            Male
7    Prussia (Germany)                            Male
8    Schleswig (Germany)                          Male
9    India                                        Male
10   Switzerland                                  Male
11   Switzerland                                  Male
12   Netherlands                                  Male
13   Netherlands                                  Male
14   Sweden                                       Male
15   Norway                                       Male
16   Faroe Islands (Denmark)                      Male
17   United Kingdom                               Male
18   France                                       Male
19   France                                       Male
20   Russian Empire (Poland)                      Female
21   Scotland                                     Male
22   France                                       Male
23   Spain                                        Male
24   Russia                                       Male
25   NA                                           NA
26   United Kingdom                               Male
27   Prussia (Germany)                            Male
28   Poland                                       Male
29   Germany                                      Male
30   Austrian Empire (Czech Republic)             Female
⋮    ⋮                                            ⋮
971  Philippines                                  Female
972  USSR (now Russia)                            Male
973  Canada                                       Male
974  United States of America                     Male
975  Netherlands                                  Male
976  United States of America                     Male
977  Sweden                                       Male
978  France                                       Male
979  United States of America                     Male
980  Austria                                      Male
981  United States of America                     Female
982  Denmark                                      Male
983  France                                       Female
984  Russia                                       Male
985  NA                                           NA
986  NA                                           NA
987  United States of America                     Male
988  United States of America                     Male
989  United States of America                     Male
990  Hungary                                      Female
991  United States of America                     Male
992  French protectorate of Tunisia (now Tunisia) Male
993  Hungary                                      Male
994  France                                       Female
995  France                                       Male
996  United States of America                     Male
997  USSR (now Russia)                            Male
998  Norway                                       Male
999  Iran                                         Female
1000 United States of America                     Female
     organization_name
1    Berlin University
2    NA
3    Marburg University
4    NA
5    NA
6    Munich University
7    Berlin University

There are 1,000 rows in this dataset.

# Q1
What is the most commonly awarded gender and birth country? Storing the string answers as `top_gender` and `top_country`.

In [77]:
#Q1

#count # sex-birth_country pairs
    #there are 154 such pairs when accounting for missing values
q1_data <- nobel %>%
    group_by(sex, birth_country) %>%
    summarize(num = n()) %>%
    ungroup() %>%
    arrange(desc(num))
q1_data

#assign specified variables
top_gender <- q1_data[1,]$sex
top_country <- q1_data[1,]$birth_country

`summarise()` has grouped output by 'sex'. You can override using the `.groups`
argument.

    sex    birth_country                                 num
1   Male   United States of America                      274
2   Male   United Kingdom                                 91
3   Male   Germany                                        65
4   Male   France                                         52
5   NA     NA                                             30
6   Male   Japan                                          28
7   Male   Sweden                                         28
8   Male   Canada                                         19
9   Male   Netherlands                                    19
10  Male   Switzerland                                    19
11  Male   Russia                                         18
12  Female United States of America                       17
13  Male   Italy                                          16
14  Male   Austria                                        15
15  Male   Norway                                         12
16  Male   Denmark                                        11
17  Male   China                                          10
18  Male   Scotland                                       10
19  Male   Australia                                       9
20  Male   Belgium                                         9
21  Male   India                                           8
22  Male   South Africa                                    8
23  Male   Germany (Poland)                                7
24  Male   Hungary                                         7
25  Male   Prussia (Germany)                               7
26  Male   Spain                                           7
27  Female France                                          6
28  Male   Egypt                                           5
29  Male   Ireland                                         5
30  Male   Prussia (Poland)                                5
⋮   ⋮      ⋮                                             ⋮
125 Male   Hungary (Slovakia)                            1
126 Male   Iceland                                       1
127 Male   Java, Dutch East Indies (Indonesia)           1
128 Male   Lebanon                                       1
129 Male   Lithuania                                     1
130 Male   Madagascar                                    1
131 Male   Mecklenburg (Germany)                         1
132 Male   Morocco                                       1
133 Male   Nigeria                                       1
134 Male   Ottoman Empire (Turkey)                       1
135 Male   Peru                                          1
136 Male   Poland (Belarus)                              1
137 Male   Poland (Lithuania)                            1
138 Male   Poland (Ukraine)                              1
139 Male   Prussia (Russia)                              1
140 Male   Russian Empire (Azerbaijan)                   1
141 Male   Russian Empire (Latvia)                       1
142 Male   Russian Empire (Lithuania)                    1
143 Male   Saint Lucia                                   1
144 Male   Southern Rhodesia (Zimbabwe)                  1
145 Male   Taiwan                                        1
146 Male   Tibet (People's Republic of China)            1
147 Male   Trinidad                                      1
148 Male   Tuscany (Italy)                               1
149 Male   USA                                           1
150 Male   Union of Soviet Socialist Republics (Belarus) 1
151 Male   Venezuela                                     1
152 Male   Vietnam                                       1
153 Male   W&uuml;rttemberg (Germany)                    1
154 Male   null                                          1

Males in the USA have won more Nobel prizes than any other 'sex'-'birth_country' pair; 274. They account for 27.4% of all Nobel prizes in this dataset.

# Q2
What decade had the highest proportion of US-born winners? Store this as an integer called `max_decade_usa`.

In [78]:
#Q2

#need to make a new column denoting the decade of the year, which spans from 1901-2023
data_mod_q2 <- nobel %>%
    mutate(decade = case_when(year<1910 ~ "1900-1909", year>1909 & year<1920 ~ "1910-1919", 
                             year>1919 & year<1930 ~ "1920-1929", year>1929 & year<1940 ~ "1930-1939", 
                             year>1939 & year<1950 ~ "1940-1949", year>1949 & year<1960 ~ "1950-1959",
                             year>1959 & year<1970 ~ "1960-1969", year>1969 & year<1980 ~ "1970-1979", 
                             year>1979 & year<1990 ~ "1980-1989", year>1989 & year<2000 ~ "1990-1999",
                             year>1999 & year<2010 ~ "2000-2009", year>2009 & year<2020 ~ "2010-2019", year>2019 ~ "2020-2029"))
#use this modified data for the purposes of Q2
q2_data <- data_mod_q2 %>%
    filter(birth_country == "United States of America") %>%
    #are 291 observations of laureates from the US
    group_by(decade) %>%
    #obtain # & proportion of such laureates per decade
    summarize(num = n(), prop = n()/291) %>%
    ungroup() %>%
    #sort in descending order
    arrange(desc(num)) %>%
    #check to ensure that the new 'prop' column sums to 100% -- GOOD
    mutate(sum_prop=sum(prop))
q2_data

#assign the specified variable
max_decade_usa <- as.integer(str_replace(q2_data[1,]$decade, "-[0-9]{4}", ""))
max_decade_usa

   decade    num prop        sum_prop
1  2000-2009 52  0.178694158 1
2  1990-1999 42  0.144329897 1
3  2010-2019 38  0.130584192 1
4  1970-1979 33  0.113402062 1
5  1980-1989 31  0.106529210 1
6  1950-1959 21  0.072164948 1
7  1960-1969 21  0.072164948 1
8  2020-2029 18  0.061855670 1
9  1930-1939 14  0.048109966 1
10 1940-1949 13  0.044673540 1
11 1920-1929  4  0.013745704 1
12 1910-1919  3  0.010309278 1
13 1900-1909  1  0.003436426 1

[1] 2000

The 2000-2009 decade accounts for the most US-born Nobel winners; 52. They account for about 18% of the 291 US-born observations.

# Q3
What decade and category pair had the highest proportion of female laureates? Store this as a list called `max_female_list` where the decade is the names of the values are `decade` and `category`.

In [79]:
#Q3
    #this question feeds off the data from Q2, can use "data_mod_q2"

q3_data <- data_mod_q2 %>%
    filter(sex == "Female") %>%
    #there are only 65 Female-laureate observations in the dataset
    group_by(decade, category) %>%
    #obtain # & proportion of such laureates per decade, category
    summarize(num = n(), prop = n()/65) %>%
    ungroup() %>%
    #sort in descending order
    arrange(desc(num)) %>%
    #check that all 'prop' values add to 100% -- GOOD
    mutate(sum_prop = sum(prop))
q3_data

#assign specified variable
max_female_list <- list(as.integer(str_replace(q3_data[1,]$decade, "-[0-9]{4}", "")), q3_data[1,]$category)
max_female_list

`summarise()` has grouped output by 'decade'. You can override using the
`.groups` argument.

   decade    category   num prop       sum_prop
1  2010-2019 Peace      5   0.07692308 1
2  2000-2009 Medicine   4   0.06153846 1
3  1970-1979 Peace      3   0.04615385 1
4  1980-1989 Medicine   3   0.04615385 1
5  1990-1999 Literature 3   0.04615385 1
6  1990-1999 Peace      3   0.04615385 1
7  2000-2009 Literature 3   0.04615385 1
8  2010-2019 Literature 3   0.04615385 1
9  2020-2029 Chemistry  3   0.04615385 1
10 1920-1929 Literature 2   0.03076923 1
11 2000-2009 Peace      2   0.03076923 1
12 2010-2019 Medicine   2   0.03076923 1
13 2020-2029 Literature 2   0.03076923 1
14 2020-2029 Peace      2   0.03076923 1
15 2020-2029 Physics    2   0.03076923 1
16 1900-1909 Literature 1   0.01538462 1
17 1900-1909 Peace      1   0.01538462 1
18 1900-1909 Physics    1   0.01538462 1
19 1910-1919 Chemistry  1   0.01538462 1
20 1930-1939 Chemistry  1   0.01538462 1
21 1930-1939 Literature 1   0.01538462 1
22 1930-1939 Peace      1   0.01538462 1
23 1940-1949 Literature 1   0.01538462 1
24 1940-1949 Medicine   1   0.01538462 1
25 1940-1949 Peace      1   0.01538462 1
26 1960-1969 Chemistry  1   0.01538462 1
27 1960-1969 Literature 1   0.01538462 1
28 1960-1969 Physics    1   0.01538462 1
29 1970-1979 Medicine   1   0.01538462 1
30 1980-1989 Peace      1   0.01538462 1
31 1990-1999 Medicine   1   0.01538462 1
32 2000-2009 Chemistry  1   0.01538462 1
33 2000-2009 Economics  1   0.01538462 1
34 2010-2019 Chemistry  1   0.01538462 1
35 2010-2019 Economics  1   0.01538462 1
36 2010-2019 Physics    1   0.01538462 1
37 2020-2029 Economics  1   0.01538462 1
38 2020-2029 Medicine   1   0.01538462 1

[[1]]
[1] 2010

[[2]]
[1] "Peace"

The most popular 'decade'-'category' pair of female Nobel prize winners was 2010-2019 & Peace prizes. There were five such observations, which account for about 7.5% of the Nobel prizes won by females.

# Q4
Who was the first woman to receive a Nobel Prize, and in what category? Save your string answers as `first_woman_name` and `first_woman_category`.

In [80]:
#Q4

q4_data <- nobel %>%
    filter(sex == "Female") %>%
    #sort chronologically over time
    arrange(year) %>%
    #select variables of relevance
    select(year:prize, prize_share, full_name:sex)
q4_data

#assigned specified variables
first_woman_name <- q4_data[1,]$full_name
first_woman_name
first_woman_category <- q4_data[1,]$category
first_woman_category

   year category   prize
1  1903 Physics    The Nobel Prize in Physics 1903
2  1905 Peace      The Nobel Peace Prize 1905
3  1909 Literature The Nobel Prize in Literature 1909
4  1911 Chemistry  The Nobel Prize in Chemistry 1911
5  1926 Literature The Nobel Prize in Literature 1926
6  1928 Literature The Nobel Prize in Literature 1928
7  1931 Peace      The Nobel Peace Prize 1931
8  1935 Chemistry  The Nobel Prize in Chemistry 1935
9  1938 Literature The Nobel Prize in Literature 1938
10 1945 Literature The Nobel Prize in Literature 1945
11 1946 Peace      The Nobel Peace Prize 1946
12 1947 Medicine   The Nobel Prize in Physiology or Medicine 1947
13 1963 Physics    The Nobel Prize in Physics 1963
14 1964 Chemistry  The Nobel Prize in Chemistry 1964
15 1966 Literature The Nobel Prize in Literature 1966
16 1976 Peace      The Nobel Peace Prize 1976
17 1976 Peace      The Nobel Peace Prize 1976
18 1977 Medicine   The Nobel Prize in Physiology or Medicine 1977
19 1979 Peace      The Nobel Peace Prize 1979
20 1982 Peace      The Nobel Peace Prize 1982
21 1983 Medicine   The Nobel Prize in Physiology or Medicine 1983
22 1986 Medicine   The Nobel Prize in Physiology or Medicine 1986
23 1988 Medicine   The Nobel Prize in Physiology or Medicine 1988
24 1991 Literature The Nobel Prize in Literature 1991
25 1991 Peace      The Nobel Peace Prize 1991
26 1992 Peace      The Nobel Peace Prize 1992
27 1993 Literature The Nobel Prize in Literature 1993
28 1995 Medicine   The Nobel Prize in Physiology or Medicine 1995
29 1996 Literature The Nobel Prize in Literature 1996
30 1997 Peace      The Nobel Peace Prize 1997
⋮  ⋮    ⋮          ⋮
36 2008 Medicine   The Nobel Prize in Physiology or Medicine 2008
37 2009 Chemistry  The Nobel Prize in Chemistry 2009
38 2009 Economics  The Sveriges Riksbank Prize in Economic Sciences 2009
39 2009 Literature The Nobel Prize in Literature 2009
40 2009 Medicine   The Nobel Prize in Physiology or Medicine 2009
41 2009 Medicine   The Nobel Prize in Physiology or Medicine 2009
42 2011 Peace      The Nobel Peace Prize 2011
43 2011 Peace      The Nobel Peace Prize 2011
44 2011 Peace      The Nobel Peace Prize 2011
45 2013 Literature The Nobel Prize in Literature 2013
46 2014 Medicine   The Nobel Prize in Physiology or Medicine 2014
47 2014 Peace      The Nobel Peace Prize 2014
48 2015 Literature The Nobel Prize in Literature 2015
49 2015 Medicine   The Nobel Prize in Physiology or Medicine 2015
50 2018 Physics    The Nobel Prize in Physics 2018
51 2018 Chemistry  The Nobel Prize in Chemistry 2018
52 2018 Peace      The Nobel Peace Prize 2018
53 2018 Literature The Nobel Prize in Literature 2018
54 2019 Economics  The Sveriges Riksbank Prize in Economic Sciences 2019
55 2020 Physics    The Nobel Prize in Physics 2020
56 2020 Chemistry  The Nobel Prize in Chemistry 2020
57 2020 Chemistry  The Nobel Prize in Chemistry 2020
58 2020 Literature The Nobel Prize in Literature 2020
59 2021 Peace      The Nobel Peace Prize 2021
60 2022 Chemistry  The Nobel Prize in Chemistry 2022
61 2022 Literature The Nobel Prize in Literature 2022
62 2023 Medicine   The Nobel Prize in Physiology or Medicine 2023
63 2023 Physics    The Nobel Prize in Physics 2023
64 2023 Peace      The Nobel Peace Prize 2023
65 2023 Economics  The Sveriges Riksbank Prize in Economic Sciences 2023
   prize_share
1  1/4
2  1/1
3  1/1
4  1/1
5  1/1
6  1/1
7  1/2
8  1/2
9  1/1
10 1/1
11 1/2
12 1/4
13 1/4
14 1/1
15 1/2
16 1/2
17 1/2
18 1/2
19 1/1
20 1/2
21 1/1
22 1/2
23 1/3
24 1/1
25 1/1
26 1/1
27 1/1
28 1/3
29 1/1
30 1/2
⋮  ⋮
36 1/4
37 1/3
38 1/2
39 1/1
40 1/3
41 1/3
42 1/3
43 1/3
44 1/3
45 1/1
46 1/4
47 1/2
48 1/1
49 1/2
50 1/4
51 1/2
52 1/2
53 1/1
54 1/3
55 1/4
56 1/2
57 1/2
58 1/1
59 1/2
60 1/3
61 1/1
62 1/2
63 1/3
64 1/1
65 1/1
   full_name
1  Marie Curie, née Sklodowska
2  Baroness Bertha Sophie Felicita von Suttner, née Countess Kinsky von Chinic und Tettau
3  Selma Ottilia Lovisa Lagerlöf
4  Marie Curie, née Sklodowska
5  Grazia Deledda
6  Sigrid Undset
7  Jane Addams
8  Irène Joliot-Curie
9  Pearl Buck
10 Gabriela Mistral
11 Emily Greene Balch
12 Gerty Theresa Cori, née Radnitz
13 Maria Goeppert Mayer
14 Dorothy Crowfoot Hodgkin
15 Nelly Sachs
16 Betty Williams
17 Mairead Corrigan
18 Rosalyn Yalow
19 Mother Teresa
20 Alva Myrdal
21 Barbara McClintock
22 Rita Levi-Montalcini
23 Gertrude B. Elion
24 Nadine Gordimer
25 Aung San Suu Kyi
26 Rigoberta Menchú Tum
27 Toni Morrison
28 Christiane Nüsslein-Volhard
29 Wislawa Szymborska
30 Jody Williams
⋮  ⋮
36 Françoise Barré-Sinoussi
37 Ada E. Yonath
38 Elinor Ostrom
39 Herta Müller
40 Elizabeth H. Blackburn
41 Carol W. Greider
42 Ellen Johnson Sirleaf
43 Leymah Gbowee
44 Tawakkol Karman
45 Alice Munro
46 May-Britt Moser
47 Malala Yousafzai
48 Svetlana Alexievich
49 Youyou Tu
50 Donna Strickland
51 Frances H. Arnold
52 Nadia Murad
53 Olga Tokarczuk
54 Esther Duflo
55 Andrea Ghez
56 Emmanuelle Charpentier
57 Jennifer A. Doudna
58 Louise Glück
59 Maria Ressa
60 Carolyn Bertozzi
61 Annie Ernaux
62 Katalin Karikó
63 Anne L’Huillier
64 Narges Mohammadi
65 Claudia Goldin
   birth_date birth_city                 birth_country
1  1867-11-07 Warsaw                     Russian Empire (Poland)
2  1843-06-09 Prague                     Austrian Empire (Czech Republic)
3  1858-11-20 Mårbacka                   Sweden
4  1867-11-07 Warsaw                     Russian Empire (Poland)
5  1871-09-27 Nuoro, Sardinia            Italy
6  1882-05-20 Kalundborg                 Denmark
7  1860-09-06 Cedarville, IL             United States of America
8  1897-09-12 Paris                      France
9  1892-06-26 Hillsboro, WV              United States of America
10 1889-04-07 Vicuña                     Chile
11 1867-01-08 Jamaica Plain, MA (Boston) United States of America
12 1896-08-15 Prague                     Austria-Hungary (Czech Republic)
13 1906-06-28 Kattowitz (Katowice)       Germany (Poland)
14 1910-05-12 Cairo                      Egypt
15 1891-12-10 Berlin                     Germany
16 1943-05-22 Belfast                    Northern Ireland
17 1944-01-27 Belfast                    Northern Ireland
18 1921-07-19 New York, NY               United States of America
19 1910-08-26 Uskup (Skopje)             Ottoman Empire (Republic of Macedonia)
20 1902-01-31 Uppsala                    Sweden
21 1902-06-16 Hartford, CT               United States of America
22 1909-04-22 Turin                      Italy
23 1918-01-23 New York, NY               United States of America
24 1923-11-20 Springs                    South Africa
25 1945-06-19 Rangoon (Yangon)           Burma (Myanmar)
26 1959-01-09 Aldea Chimel               Guatemala
27 1931-02-18 Lorain, OH                 United States of America
28 1942-10-20 Magdeburg                  Germany
29 1923-07-02 Bnin (Kórnik)              Poland
30 1950-10-09 Putney, VT                 United States of America
⋮  ⋮          ⋮                          ⋮
36 1947-07-30 Paris                      France
37 1939-06-22 Jerusalem                  British Mandate of Palestine (Israel)
38 1933-08-07 Los Angeles, CA            United States of America
39 1953-08-17 Nitzkydorf, Banat          Romania
40 1948-11-26 Hobart, Tasmania           Australia
41 1961-04-15 San Diego, CA              United States of America
42 1938-10-29 Monrovia                   Liberia
43 1972-02-01 Monrovia                   Liberia
44 1979-02-07 Ta'izz                     Yemen
45 1931-07-10 Wingham                    Canada
46 1963-01-04 Fosnavåg                   Norway
47 1997-07-12 Mingora                    Pakistan
48 1948-05-31 Ivano-Frankivsk            Ukraine
49 1930-12-30 Zhejiang Ningbo            China
50 1959-05-27 Guelph                     Canada
51 1956-07-25 Pittsburgh, PA             United States of America
52 <NA>       Kojo                       Iraq
53 1962-01-29 Sulechów                   Poland
54 1972-10-25 Paris                      France
55 1965-06-16 New York, NY               United States of America
56 1968-12-11 Juvisy-sur-Orge            France
57 1964-02-19 Washington, D.C.           United States of America
58 1943-04-22 New York, NY               United States of America
59 1963-10-02 Manila                     Philippines
60 1966-10-10 Boston, MA                 United States of America
61 1940-09-01 Lillebonne                 France
62 1955-01-17 Szolnok                    Hungary
63 1958-08-16 Paris                      France
64 1972-04-21 Zanjan                     Iran
65 <NA>       New York, NY               United States of America
   sex
1  Female
2  Female
3  Female
4  Female
5  Female
6  Female
7  Female
8  Female
9  Female
10 Female
11 Female
12 Female
13 Female
14 Female
15 Female
16 Female
17 Female
18 Female
19 Female
20 Female
21 Female
22 Female
23 Female
24 Female
25 Female
26 Female
27 Female
28 Female
29 Female
30 Female
⋮  ⋮
36 Female
37 Female
38 Female
39 Female
40 Female
41 Female
42 Female
43 Female
44 Female
45 Female
46 Female
47 Female
48 Female
49 Female
50 Female
51 Female
52 Female
53 Female
54 Female
55 Female
56 Female
57 Female
58 Female
59 Female
60 Female
61 Female
62 Female
63 Female
64 Female
65 Female

[1] "Marie Curie, née Sklodowska"

[1] "Physics"

Marie Curie was the first woman to win a Nobel prize. She won her first, & first for all women, in 1903 in Physics. She won a 2nd Nobel prize, the fourth for ll women, in 1911 in Chemistry.

# Q5
Which individuals or organizations have won multiple Nobel Prizes throughout the years? Store the full names in a list named `repeats`.

In [81]:
#Q5

q5_data <- nobel %>%
    group_by(laureate_id) %>%
    #count # observations--# Nobel prize--per 'laureate_id'
    summarize(num_nobels = n()) %>%
    ungroup() %>%
    #filter for 'laureate_id's with multiple observations -- are 7 such id's
    filter(num_nobels>1) %>%
    #sort in descending order
    arrange(desc(num_nobels)) %>%
    #use a join to get other information (i.e. name, organization, ...)
    inner_join(orig_data, by=c("laureate_id"))
q5_data

#assign specified variable
repeats <- as.list(unique(q5_data$full_name))
repeats

   laureate_id num_nobels year category  prize
1  482         3          1917 Peace     The Nobel Peace Prize 1917
2  482         3          1944 Peace     The Nobel Peace Prize 1944
3  482         3          1963 Peace     The Nobel Peace Prize 1963
4    6         2          1903 Physics   The Nobel Prize in Physics 1903
5    6         2          1911 Chemistry The Nobel Prize in Chemistry 1911
6   66         2          1956 Physics   The Nobel Prize in Physics 1956
7   66         2          1972 Physics   The Nobel Prize in Physics 1972
8  217         2          1954 Chemistry The Nobel Prize in Chemistry 1954
9  217         2          1962 Peace     The Nobel Peace Prize 1962
10 222         2          1958 Chemistry The Nobel Prize in Chemistry 1958
11 222         2          1980 Chemistry The Nobel Prize in Chemistry 1980
12 515         2          1954 Peace     The Nobel Peace Prize 1954
13 515         2          1981 Peace     The Nobel Peace Prize 1981
14 743         2          2001 Chemistry The Nobel Prize in Chemistry 2001
15 743         2          2022 Chemistry The Nobel Prize in Chemistry 2022
   motivation
1  NA
2  NA
3  NA
4  "in recognition of the extraordinary services they have rendered by their joint researches on the radiation phenomena discovered by Professor Henri Becquerel"
5  "in recognition of her services to the advancement of chemistry by the discovery of the elements radium and polonium, by the isolation of radium and the study of the nature and compounds of this remarkable element"
6  "for their researches on semiconductors and their discovery of the transistor effect"
7  "for their jointly developed theory of superconductivity, usually called the BCS-theory"
8  "for his research into the nature of the chemical bond and its application to the elucidation of the structure of complex substances"
9  NA
10 "for his work on the structure of proteins, especially that of insulin"
11 "for their contributions concerning the determination of base sequences in nucleic acids"
12 NA
13 NA
14 "for his work on chirally catalysed oxidation reactions"
15 "for the development of click chemistry and bioorthogonal chemistry"
   prize_share laureate_type
1  1/1         Organization
2  1/1         Organization
3  1/2         Organization
4  1/4         Individual
5  1/1         Individual
6  1/3         Individual
7  1/3         Individual
8  1/1         Individual
9  1/1         Individual
10 1/1         Individual
11 1/4         Individual
12 1/1         Organization
13 1/1         Organization
14 1/2         Individual
15 1/3         Individual
   full_name
1  Comité international de la Croix Rouge (International Committee of the Red Cross)
2  Comité international de la Croix Rouge (International Committee of the Red Cross)
3  Comité international de la Croix Rouge (International Committee of the Red Cross)
4  Marie Curie, née Sklodowska
5  Marie Curie, née Sklodowska
6  John Bardeen
7  John Bardeen
8  Linus Carl Pauling
9  Linus Carl Pauling
10 Frederick Sanger
11 Frederick Sanger
12 Office of the United Nations High Commissioner for Refugees (UNHCR)
13 Office of the United Nations High Commissioner for Refugees (UNHCR)
14 K. Barry Sharpless
15 Barry Sharpless
   birth_date birth_city       birth_country            sex
1  <NA>       NA               NA                       NA
2  <NA>       NA               NA                       NA
3  <NA>       NA               NA                       NA
4  1867-11-07 Warsaw           Russian Empire (Poland)  Female
5  1867-11-07 Warsaw           Russian Empire (Poland)  Female
6  1908-05-23 Madison, WI      United States of America Male
7  1908-05-23 Madison, WI      United States of America Male
8  1901-02-28 Portland, OR     United States of America Male
9  1901-02-28 Portland, OR     United States of America Male
10 1918-08-13 Rendcombe        United Kingdom           Male
11 1918-08-13 Rendcombe        United Kingdom           Male
12 <NA>       NA               NA                       NA
13 <NA>       NA               NA                       NA
14 1941-04-28 Philadelphia, PA United States of America Male
15 1941-04-28 Philadelphia, PA United States of America Male
   organization_name                            organization_city
1  NA                                           NA
2  NA                                           NA
3  NA                                           NA
4  NA                                           NA
5  Sorbonne University                          Paris
6  University of Illinois                       Urbana, IL
7  University of Illinois                       Urbana, IL
8  California Institute of Technology (Caltech) Pasadena, CA
9  California Institute of Technology (Caltech) Pasadena, CA
10 University of Cambridge                      Cambridge
11 MRC Laboratory of Molecular Biology          Cambridge
12 NA                                           NA
13 NA                                           NA
14 The Scripps Research Institute               La Jolla, CA
15 Scripps Research                             La Jolla, CA
   organization_country     death_date death_city  death_country
1  NA                       <NA>       NA          NA
2  NA                       <NA>       NA          NA
3  NA                       <NA>       NA          NA
4  NA                       1934-07-04 Sallanches  France
5  France                   1934-07-04 Sallanches  France
6  United States of America 1991-01-30 Boston, MA  United States of America
7  United States of America 1991-01-30 Boston, MA  United States of America
8  United States of America 1994-08-19 Big Sur, CA United States of America
9  United States of America 1994-08-19 Big Sur, CA United States of America
10 United Kingdom           2013-11-19 Cambridge   United Kingdom
11 United Kingdom           2013-11-19 Cambridge   United Kingdom
12 NA                       <NA>       NA          NA
13 NA                       <NA>       NA          NA
14 United States of America <NA>       NA          NA
15 United States of America <NA>       NA          NA

[[1]]
[1] "Comité international de la Croix Rouge (International Committee of the Red Cross)"

[[2]]
[1] "Marie Curie, née Sklodowska"

[[3]]
[1] "John Bardeen"

[[4]]
[1] "Linus Carl Pauling"

[[5]]
[1] "Frederick Sanger"

[[6]]
[1] "Office of the United Nations High Commissioner for Refugees (UNHCR)"

[[7]]
[1] "K. Barry Sharpless"

[[8]]
[1] "Barry Sharpless"

In this dataset, there are seven unique individuals/organizations that won multiple Nobel prizes. Six of them won two, & the Comité international de la Croix Rouge (International Committee of the Red Cross) won three. Note that the `repeats` list contains eight unique elements, which is because the dataset has an inconsistency in the 'full_name' column regarding Barry Sharpless. This individual's 'laureate_id' corresponds to two different 'full_name's.